apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "image-registry"
  namespace: "openshift-image-registry"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: <your_storage_class_that_provides_RWM>

---

apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  finalizers:
  - imageregistry.operator.openshift.io/finalizer
  name: cluster
  selfLink: /apis/imageregistry.operator.openshift.io/v1/configs/cluster
spec:
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  proxy: {}
  replicas: 1
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  rolloutStrategy: RollingUpdate
  storage:
    managementState: Unmanaged
    pvc:
      claim: image-registry
  unsupportedConfigOverrides: null

